Shops = Shops or {}

Shops.Shops = {
    ['uwucafe'] = {
        label = "uWu Cafe",
        slots = 20,
        items = {
            [1] = {
                name = "milk",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 1,
            },
            [2] = {
                name = "egg",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 2,
            },
            [3] = {
                name = "flour",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 3,
            },
            [4] = {
                name = "tuna",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 4,
            },
            [5] = {
                name = "rice",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 5,
            },
            [6] = {
                name = "avocado",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 6,
            },
            [7] = {
                name = "nori",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 7,
            },
            [8] = {
                name = "headoflettuce",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 8,
            },
            [9] = {
                name = "tofu",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 9,
            },
            [10] = {
                name = "chocolate",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 10,
            },
            [11] = {
                name = "umami",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 11,
            },
            [12] = {
                name = "tapiokaballs",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 12,
            },
            [13] = {
                name = "tea",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 13,
            },
            [14] = {
                name = "water_bottle",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 14,
            },
            [15] = {
                name = "uwubentobox",
                price = 0,
                amount = 50,
                info = {},
                type = "item",
                slot = 15,
            },
            [16] = {
                name = "misopaste",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 16,
            },
            [17] = {
                name = "rawsugar",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 17,
            },
            [18] = {
                name = "sprinkles",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 18,
            },
            [19] = {
                name = "vanillabean",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 19,
            },
            [20] = {
                name = "uwumystery",
                price = 30,
                amount = 50,
                info = {},
                type = "item",
                slot = 20,
            },
        },
    },
    ['popsdiner'] = {
        label = "Pop's Diner",
        slots = 20,
        items = {
            [1] = {
                name = "milk",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 1,
            },
            [2] = {
                name = "coffeegrounds",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 2,
            },
            [3] = {
                name = "greenteapowder",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 3,
            },
            [4] = {
                name = "chocolatepowder",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 4,
            },
            [5] = {
                name = "raw_bacon",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 5,
            },
            [6] = {
                name = "egg",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 6,
            },
            [7] = {
                name = "potato",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 7,
            },
            [8] = {
                name = "flour",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 8,
            },
            [9] = {
                name = "chicken",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 9,
            },
            [10] = {
                name = "loaf-of-bread",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 10,
            },
            [11] = {
                name = "popssauce",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 11,
            },
            [12] = {
                name = "soda-syrup",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 12,
            },
            [13] = {
                name = "water_bottle",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 13,
            },
            [14] = {
                name = "cheese",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 14,
            },
            [15] = {
                name = "applepie",
                price = 200,
                amount = 50,
                info = {},
                type = "item",
                slot = 15,
            },
            [16] = {
                name = "peachcobbler",
                price = 200,
                amount = 50,
                info = {},
                type = "item",
                slot = 16,
            },
            [17] = {
                name = "coconutcreampie",
                price = 200,
                amount = 50,
                info = {},
                type = "item",
                slot = 17,
            },
            [18] = {
                name = "takeout",
                price = 0,
                amount = 50,
                info = {},
                type = "item",
                slot = 18,
            },
            [19] = {
                name = "mixedlettuce",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 19,
            },
            [20] = {
                name = "pdmystery",
                price = 30,
                amount = 50,
                info = {},
                type = "item",
                slot = 20,
            },
        }
    },
    ['burgershot'] = {
        label = "BurgerShot",
        slots = 11,
        items = {
            [1] = {
                name = "tomato",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 1,
            },
            [2] = {
                name = "headoflettuce",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 2,
            },
            [3] = {
                name = "potato",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 3,
            },
            [4] = {
                name = "burger-bun",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 4,
            },
            [5] = {
                name = "soda-syrup",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 5,
            },
            [6] = {
                name = "milk",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 6,
            },
            [7] = {
                name = "water_bottle",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 7,
            },
            [8] = {
                name = "burger-mshakeformula",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 8,
            },
            [9] = {
                name = "burger-raw",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 9,
            },
            [10] = {
                name = "burger-murdermeal",
                price = 0,
                amount = 50,
                info = {},
                type = "item",
                slot = 10,
            },
            [11] = {
                name = "bsmystery",
                price = 30,
                amount = 50,
                info = {},
                type = "item",
                slot = 11,
            },
        }
    },
    ['pizzathis'] = {
        label = "Pizza This",
        slots = 12,
        items = {
            [1] = {
                name = "pizza-dough",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 1,
            },
            [2] = {
                name = "mozzarella-cheese",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 2,
            },
            [3] = {
                name = "pepperoni-stick",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 3,
            },
            [4] = {
                name = "energy-shot",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 4,
            },
            [5] = {
                name = "tomato",
                price = 10,
                amount = 50,
                info = {},
                type = "item",
                slot = 5,
            },
            [6] = {
                name = "loaf-of-bread",
                price = 25,
                amount = 50,
                info = {},
                type = "item",
                slot = 6,
            },
            [7] = {
                name = "butter-stick",
                price = 25,
                amount = 50,
                info = {},
                type = "item",
                slot = 7,
            },
            [8] = {
                name = "cooking-spices",
                price = 25,
                amount = 50,
                info = {},
                type = "item",
                slot = 8,
            },
            [9] = {
                name = "packaged-ham",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 9,
            },
            [10] = {
                name = "pizzathis-pineapple-slice",
                price = 20,
                amount = 50,
                info = {},
                type = "item",
                slot = 10,
            },
            [11] = {
                name = "pizzabox",
                price = 0,
                amount = 50,
                info = {},
                type = "item",
                slot = 11,
            },
            [12] = {
                name = "ptmystery",
                price = 30,
                amount = 50,
                info = {},
                type = "item",
                slot = 12,
            },
        }
    },
    ['record'] = {
        label = "Record A Studio",
        slots = 12,
        items = {
            [1] = {
                name = "boombox",
                price = 1000,
                amount = 50,
                info = {},
                type = "item",
                slot = 1,
            },
            [2] = {
                name = "zellteasertape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 2,
            },
            [3] = {
                name = "emptybed",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 3,
            },
            [4] = {
                name = "bangintape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 4,
            },
            [5] = {
                name = "creepingouttape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 5,
            },
            [6] = {
                name = "drilltape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 6,
            },
            [7] = {
                name = "lofiandchilltape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 7,
            },
            [8] = {
                name = "atmospheretape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 8,
            },
            [9] = {
                name = "californiaghosttape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 9,
            },
            [10] = {
                name = "darkmagictape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 10,
            },
            [11] = {
                name = "realhiphoptape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 11,
            },
            [12] = {
                name = "winterbellstape",
                price = 500,
                amount = 50,
                info = {},
                type = "item",
                slot = 12,
            },
        }
    }
}
Shops.Locations = {
    [1] = { -- pizza this
        coords = vector3(802.61, -756.82, 26.78),
        length = 0.6,
        width = 3.0,
        name = "pizzathisshop",
        heading = 0,
        debugPoly = false,
        minZ=25.98,
        maxZ=28.58,
        job = "pizzathis",
        location = "pizzathis",
        label = "Pizza This Stock",
    },
    [2] = { -- uwu
        coords = vector3(-598.53, -1068.41, 22.34),
        length = 5.2,
        width = 1.4,
        name = "uwucafeshop",
        heading = 270,
        debugPoly = false,
        minZ=21.34,
        maxZ=27.74,
        job = "uwucafe",
        location = "uwucafe",
        label = "uWu Cafe Stock",
    },
    [3] = { -- pops
        coords = vector3(1596.96, 6453.34, 25.32),
        length = 2.2,
        width = 1.4,
        name = "popsdinershop",
        heading = 335,
        debugPoly = false,
        minZ=24.32,
        maxZ=26.72,
        job = "popsdiner",
        location = "popsdiner",
        label = "Pop's Diner Stock",
    },
    [4] = { -- bs
        coords = vector3(-1205.13, -893.73, 14.0),
        length = 3.0,
        width = 1.0,
        name = "burgershotshop",
        heading = 0,
        debugPoly = false,
        minZ=13.0,
        maxZ=15.4,
        job = "burgershot",
        location = "burgershot",
        label = "BurgerShot Stock",
    },
    [5] = { -- record
        coords = vector3(488.41, -84.77, 58.19),
        length = 1.0,
        width = 1.4,
        name = "recordshop",
        heading = 340,
        debugPoly = false,
        minZ=57.59,
        maxZ=58.39,
        job = "record",
        location = "record",
        label = "Record Stock",
    },
}